version: '3'
services:
  device1:
    image: device-image-1
    build:
      context: ./device
    depends_on:
      - load_balancer
    environment:
      - DEVICE_ID=1
    ports:
      - "5051:5002"
    volumes:
      - ./device:/app
     

  device2:
    image: device-image-2
    build:
      context: ./device
    depends_on:
      - load_balancer
    environment:
      - DEVICE_ID=2
    ports:
      - "5052:5002"
    volumes:
      - ./device:/app

  device3:
    image: device-image-3
    build:
      context: ./device
    depends_on:
      - load_balancer
    environment:
      - DEVICE_ID=3      
    ports:
      - "5053:5002"
    volumes:
      - ./device:/app

  load_balancer:
    image: load_balancer-image
    build:
      context: ./load_balancer
    depends_on:
      - server
    environment:
      - DEVICE_HOST=device
    ports:
      - "5000:5000"
    volumes:
      - ./load_balancer:/app

  server:
    image: server-image
    build:
      context: ./server
    environment:
      - DEVICE_HOST=load_balancer
    ports:
      - "5001:5001"
    volumes:
      - ./server:/app    
