version: '3'
services:
  device1:
    image: device-image
    build:
      context: ./device
    environment:
      - DEVICE_ID=1
    ports:
      - "6001:5000"  # Map host port 6001 to container port 5000
    depends_on:
      - load_balancer

  device2:
    image: device-image
    build:
      context: ./device
    environment:
      - DEVICE_ID=2
    ports:
      - "6002:5000"  # Map host port 6002 to container port 5000
    depends_on:
      - load_balancer

  device3:
    image: device-image
    build:
      context: ./device
    environment:
      - DEVICE_ID=3
    ports:
      - "6003:5000"  # Map host port 6003 to container port 5000
    depends_on:
      - load_balancer

  load_balancer:
    image: load_balancer-image
    build:
      context: ./load_balancer
    environment:
      - DEVICE_HOST=device
    ports:
      - "5000:5000"

  server:
    image: server-image
    build:
      context: ./server
    environment:
      - DEVICE_HOST=load_balancer
    ports:
      - "5001:5001"
    depends_on:
      - load_balancer
